//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetRu.Clients.UI.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DotNetRu.Clients.UI.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        public static string AboutDotNetRu {
            get {
                return ResourceManager.GetString("AboutDotNetRu", resourceCulture);
            }
        }
        
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        public static string Abstract {
            get {
                return ResourceManager.GetString("Abstract", resourceCulture);
            }
        }
        
        public static string AddedToCalendar {
            get {
                return ResourceManager.GetString("AddedToCalendar", resourceCulture);
            }
        }
        
        public static string AddToCalendar {
            get {
                return ResourceManager.GetString("AddToCalendar", resourceCulture);
            }
        }
        
        public static string AllDay {
            get {
                return ResourceManager.GetString("AllDay", resourceCulture);
            }
        }
        
        public static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string CodeFromSession {
            get {
                return ResourceManager.GetString("CodeFromSession", resourceCulture);
            }
        }
        
        public static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        public static string DotNetRu {
            get {
                return ResourceManager.GetString("DotNetRu", resourceCulture);
            }
        }
        
        public static string EkbDotNet {
            get {
                return ResourceManager.GetString("EkbDotNet", resourceCulture);
            }
        }
        
        public static string Enter_search_term {
            get {
                return ResourceManager.GetString("Enter search term", resourceCulture);
            }
        }
        
        public static string Enter_speaker_fullname {
            get {
                return ResourceManager.GetString("Enter speaker fullname", resourceCulture);
            }
        }
        
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        public static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        public static string IssueTracker {
            get {
                return ResourceManager.GetString("IssueTracker", resourceCulture);
            }
        }
        
        public static string Krasnoyarsk {
            get {
                return ResourceManager.GetString("Krasnoyarsk", resourceCulture);
            }
        }
        
        public static string KrdDotNet {
            get {
                return ResourceManager.GetString("KrdDotNet", resourceCulture);
            }
        }
        
        public static string KryDotNet {
            get {
                return ResourceManager.GetString("KryDotNet", resourceCulture);
            }
        }
        
        public static string KznDotNet {
            get {
                return ResourceManager.GetString("KznDotNet", resourceCulture);
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string LoadingFriends {
            get {
                return ResourceManager.GetString("LoadingFriends", resourceCulture);
            }
        }
        
        public static string LoadingMeetups {
            get {
                return ResourceManager.GetString("LoadingMeetups", resourceCulture);
            }
        }
        
        public static string LoadingSpeakers {
            get {
                return ResourceManager.GetString("LoadingSpeakers", resourceCulture);
            }
        }
        
        public static string LoadingTalks {
            get {
                return ResourceManager.GetString("LoadingTalks", resourceCulture);
            }
        }
        
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        public static string Meetup {
            get {
                return ResourceManager.GetString("Meetup", resourceCulture);
            }
        }
        
        public static string Meetups {
            get {
                return ResourceManager.GetString("Meetups", resourceCulture);
            }
        }
        
        public static string MskDotNet {
            get {
                return ResourceManager.GetString("MskDotNet", resourceCulture);
            }
        }
        
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        public static string NnvDotNet {
            get {
                return ResourceManager.GetString("NnvDotNet", resourceCulture);
            }
        }
        
        public static string NoTalksFound {
            get {
                return ResourceManager.GetString("NoTalksFound", resourceCulture);
            }
        }
        
        public static string NskDotNet {
            get {
                return ResourceManager.GetString("NskDotNet", resourceCulture);
            }
        }
        
        public static string OmsDotNet {
            get {
                return ResourceManager.GetString("OmsDotNet", resourceCulture);
            }
        }
        
        public static string OpenSourceNotice {
            get {
                return ResourceManager.GetString("OpenSourceNotice", resourceCulture);
            }
        }
        
        public static string OurCommunities {
            get {
                return ResourceManager.GetString("OurCommunities", resourceCulture);
            }
        }
        
        public static string PnzDotNet {
            get {
                return ResourceManager.GetString("PnzDotNet", resourceCulture);
            }
        }
        
        public static string PresentationSlides {
            get {
                return ResourceManager.GetString("PresentationSlides", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        public static string RemovedFromCalendar {
            get {
                return ResourceManager.GetString("RemovedFromCalendar", resourceCulture);
            }
        }
        
        public static string RemoveFromCalendar {
            get {
                return ResourceManager.GetString("RemoveFromCalendar", resourceCulture);
            }
        }
        
        public static string SamDotNet {
            get {
                return ResourceManager.GetString("SamDotNet", resourceCulture);
            }
        }
        
        public static string SarDotNet {
            get {
                return ResourceManager.GetString("SarDotNet", resourceCulture);
            }
        }
        
        public static string SeeAlso {
            get {
                return ResourceManager.GetString("SeeAlso", resourceCulture);
            }
        }
        
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        public static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        public static string SpbDotNet {
            get {
                return ResourceManager.GetString("SpbDotNet", resourceCulture);
            }
        }
        
        public static string SpeakerInfo {
            get {
                return ResourceManager.GetString("SpeakerInfo", resourceCulture);
            }
        }
        
        public static string Speakers {
            get {
                return ResourceManager.GetString("Speakers", resourceCulture);
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string Talk {
            get {
                return ResourceManager.GetString("Talk", resourceCulture);
            }
        }
        
        public static string TalkRecording {
            get {
                return ResourceManager.GetString("TalkRecording", resourceCulture);
            }
        }
        
        public static string Talks {
            get {
                return ResourceManager.GetString("Talks", resourceCulture);
            }
        }
        
        public static string TechnologyUsed {
            get {
                return ResourceManager.GetString("TechnologyUsed", resourceCulture);
            }
        }
        
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        public static string ToBeAnnounced {
            get {
                return ResourceManager.GetString("ToBeAnnounced", resourceCulture);
            }
        }
        
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        public static string UfaDotNet {
            get {
                return ResourceManager.GetString("UfaDotNet", resourceCulture);
            }
        }
        
        public static string Venue {
            get {
                return ResourceManager.GetString("Venue", resourceCulture);
            }
        }
        
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
