//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetRu.Clients.UI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetRu.Clients.UI.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About App.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About DotNetRu.
        /// </summary>
        public static string AboutDotNetRu {
            get {
                return ResourceManager.GetString("AboutDotNetRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian .NET community is a group of independent communities of .NET developers from Russia. We unite people around .Net platform to contribute to the experience and knowledge exchange. We hold meetings regularly to share news and best practices in software development! Find our more at .
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        public static string Abstract {
            get {
                return ResourceManager.GetString("Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day.
        /// </summary>
        public static string AllDay {
            get {
                return ResourceManager.GetString("AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code from Session.
        /// </summary>
        public static string CodeFromSession {
            get {
                return ResourceManager.GetString("CodeFromSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        public static string CopiedToClipboard {
            get {
                return ResourceManager.GetString("CopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by DotNetRu Team with &lt;3.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DotNetRu mobile app was handcrafted by DotNetRu, based on the great work done by Xamarin.
        ///
        ///DotNetRu Team
        ///
        ///Pavel Fedotovsky
        ///Anatoly Kulakov
        ///Yury Belousov
        ///Sergey Polezhaev.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DotNetRu.
        /// </summary>
        public static string DotNetRu {
            get {
                return ResourceManager.GetString("DotNetRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        public static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an issue.
        /// </summary>
        public static string IssueTracker {
            get {
                return ResourceManager.GetString("IssueTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krasnoyarsk.
        /// </summary>
        public static string Krasnoyarsk {
            get {
                return ResourceManager.GetString("Krasnoyarsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krasnodar.
        /// </summary>
        public static string KrdDotNet {
            get {
                return ResourceManager.GetString("KrdDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krasnoyarsk.
        /// </summary>
        public static string KryDotNet {
            get {
                return ResourceManager.GetString("KryDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazan.
        /// </summary>
        public static string KznDotNet {
            get {
                return ResourceManager.GetString("KznDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Social Feed....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading meetups...
        /// </summary>
        public static string LoadingMeetups {
            get {
                return ResourceManager.GetString("LoadingMeetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading talks....
        /// </summary>
        public static string LoadingTalks {
            get {
                return ResourceManager.GetString("LoadingTalks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetup.
        /// </summary>
        public static string Meetup {
            get {
                return ResourceManager.GetString("Meetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetups.
        /// </summary>
        public static string Meetups {
            get {
                return ResourceManager.GetString("Meetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moscow.
        /// </summary>
        public static string MskDotNet {
            get {
                return ResourceManager.GetString("MskDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nizhny Novgorod.
        /// </summary>
        public static string NnvDotNet {
            get {
                return ResourceManager.GetString("NnvDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No talks found.
        /// </summary>
        public static string NoTalksFound {
            get {
                return ResourceManager.GetString("NoTalksFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novosibirsk.
        /// </summary>
        public static string NskDotNet {
            get {
                return ResourceManager.GetString("NskDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omsk.
        /// </summary>
        public static string OmsDotNet {
            get {
                return ResourceManager.GetString("OmsDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Source Notice.
        /// </summary>
        public static string OpenSourceNotice {
            get {
                return ResourceManager.GetString("OpenSourceNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our communities.
        /// </summary>
        public static string OurCommunities {
            get {
                return ResourceManager.GetString("OurCommunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penza.
        /// </summary>
        public static string PnzDotNet {
            get {
                return ResourceManager.GetString("PnzDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation Slides.
        /// </summary>
        public static string PresentationSlides {
            get {
                return ResourceManager.GetString("PresentationSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samara.
        /// </summary>
        public static string SamDotNet {
            get {
                return ResourceManager.GetString("SamDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saratov.
        /// </summary>
        public static string SarDotNet {
            get {
                return ResourceManager.GetString("SarDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See also.
        /// </summary>
        public static string SeeAlso {
            get {
                return ResourceManager.GetString("SeeAlso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saint Petersburg.
        /// </summary>
        public static string SpbDotNet {
            get {
                return ResourceManager.GetString("SpbDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker.
        /// </summary>
        public static string SpeakerInfo {
            get {
                return ResourceManager.GetString("SpeakerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers.
        /// </summary>
        public static string Speakers {
            get {
                return ResourceManager.GetString("Speakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk.
        /// </summary>
        public static string Talk {
            get {
                return ResourceManager.GetString("Talk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk Recording.
        /// </summary>
        public static string TalkRecording {
            get {
                return ResourceManager.GetString("TalkRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talks.
        /// </summary>
        public static string Talks {
            get {
                return ResourceManager.GetString("Talks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Used.
        /// </summary>
        public static string TechnologyUsed {
            get {
                return ResourceManager.GetString("TechnologyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspired by James Montemagno.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be announced.
        /// </summary>
        public static string ToBeAnnounced {
            get {
                return ResourceManager.GetString("ToBeAnnounced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ufa.
        /// </summary>
        public static string UfaDotNet {
            get {
                return ResourceManager.GetString("UfaDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        public static string Venue {
            get {
                return ResourceManager.GetString("Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
