//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinEvolve.Clients.Portable.ApplicationResources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinEvolve.Clients.Portable.ApplicationResources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian .NET community is a group of independent communities of .NET developers from Russia. We unite people around .Net platform to contribute to the experience and knowledge exchange. We hold meetings regularly to share news and best practices in software development! .
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        internal static string Abstract {
            get {
                return ResourceManager.GetString("Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        internal static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by DotNetRu Team with &lt;3.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend.
        /// </summary>
        internal static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        internal static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        internal static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetups.
        /// </summary>
        internal static string Meetups {
            get {
                return ResourceManager.GetString("Meetups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open source on Github!.
        /// </summary>
        internal static string OpenSource {
            get {
                return ResourceManager.GetString("OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Source Notice.
        /// </summary>
        internal static string OpenSourceNotice {
            get {
                return ResourceManager.GetString("OpenSourceNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presentation Slides.
        /// </summary>
        internal static string PresentationSlides {
            get {
                return ResourceManager.GetString("PresentationSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        internal static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        internal static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers.
        /// </summary>
        internal static string Speakers {
            get {
                return ResourceManager.GetString("Speakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk.
        /// </summary>
        internal static string Talk {
            get {
                return ResourceManager.GetString("Talk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk Recording.
        /// </summary>
        internal static string TalkRecording {
            get {
                return ResourceManager.GetString("TalkRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Used.
        /// </summary>
        internal static string TechnologyUsed {
            get {
                return ResourceManager.GetString("TechnologyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        internal static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big thanks to James Montemagno.
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue.
        /// </summary>
        internal static string Venue {
            get {
                return ResourceManager.GetString("Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
